# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-07 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grofers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='key',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
